services:
  - type: web
    name: sahjanand-api
    env: python
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql+asyncpg://postgres:Bhavarth%400903@db.zvutmajpsebvqdsshfhq.supabase.co:5432/postgres
      - key: SUPABASE_URL
        value: https://zvutmajpsebvqdsshfhq.supabase.co
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://sahjanand-api.onrender.com
      - key: PRODUCTION_URL
        value: https://sahjanand-api.onrender.com
      - key: PYTHON_VERSION
        value: "3.12.0"
